name: Vercel Deploy

on:
  push:
    branches: ["main"]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Push entire repository to another repository
        uses: cpina/github-action-push-to-another-repository@main
        env:
          API_TOKEN_GITHUB: ${{ secrets.AUTO_ACTIONS }}
        with:
          source-directory: "."
          destination-github-username: "she0108"
          destination-repository-name: "linkmoa-frontend"
          user-email: ${{ secrets.EMAIL }}
          commit-message: ${{ github.event.head_commit.message || 'Default commit message' }}
          target-branch: main
